---
application:
  name: "simple-example-gin-with-postgresql"
  project: "Test"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "Test"
  version: "12"
routers:
- name: "main-simple-example-gin-with-postgresql"
  routes:
  - application_name: "simple-example-gin-with-postgresql"
    paths:
    - "/*"
